import RPi.GPIO as gpio
import time

gpio.setup(3, gpio.OUT)
gpio.setup(5, gpio.OUT)
gpio.setup(7, gpio.OUT)
gpio.setup(11, gpio.OUT)
gpio.setup(13, gpio.OUT)
j = str(input("Digite um nome: "))  
time.sleep(1)
        
for i in j:
          if i == "a": # ( .- )
              gpio.output(5, 1)
              time.sleep(0.5)
              gpio.output(5, 0)
              time.sleep(0.5)
              gpio.output(3, 1)
              gpio.output(5, 1)
              gpio.output(7, 1)
              time.sleep(0.5)
              gpio.output(3, 0)
              gpio.output(5, 0)
              gpio.output(7, 0)
              time.sleep(1)
          if i == "b": # ( -... )
              gpio.output(3, 1)
              gpio.output(5, 1)
              gpio.output(7, 1)
              time.sleep(0.5)
              gpio.output(3, 0)
              gpio.output(5, 0)
              gpio.output(7, 0)
              time.sleep(0.5)
              gpio.output(5, 1)
              time.sleep(0.5)
              gpio.output(5, 0)
              time.sleep(0.5)
              gpio.output(5, 1)
              time.sleep(0.5)
              gpio.output(5, 0)
              time.sleep(0.5)
              gpio.output(5, 1)
              time.sleep(0.5)
              gpio.output(5, 0)
              time.sleep(1)
          if i == "c": # ( -.-. )
              gpio.output(3, 1)
              gpio.output(5, 1)
              gpio.output(7, 1)
              time.sleep(0.5)
              gpio.output(3, 0)
              gpio.output(5, 0)
              gpio.output(7, 0)
              time.sleep(0.5)
              gpio.output(5, 1)
              time.sleep(0.5)
              gpio.output(5, 0)
              time.sleep(0.5)
              gpio.output(3, 1)
              gpio.output(5, 1)
              gpio.output(7, 1)
              time.sleep(0.5)
              gpio.output(3, 0)
              gpio.output(5, 0)
              gpio.output(7, 0)
              time.sleep(0.5)
              gpio.output(5, 1)
              time.sleep(0.5)
              gpio.output(5, 0)
              time.sleep(1)
          if i == "d": # ( -.. )
              gpio.output(3, 1)
              gpio.output(5, 1)
              gpio.output(7, 1)
              time.sleep(0.5)
              gpio.output(3, 0)
              gpio.output(5, 0)
              gpio.output(7, 0)
              time.sleep(0.5)
              gpio.output(5, 1)
              time.sleep(0.5)
              gpio.output(5, 0)
              time.sleep(0.5)
              gpio.output(5, 1)
              time.sleep(0.5)
              gpio.output(5, 0)
              time.sleep(1)
          if i == "e": # ( . )
              gpio.output(5, 1)
              time.sleep(0.5)
              gpio.output(5, 0)
              time.sleep(1)
          if i == "f": # ( ..-. )
              gpio.output(5, 1)
              time.sleep(0.5)
              gpio.output(5, 0)
              time.sleep(0.5)
              gpio.output(5, 1)
              time.sleep(0.5)
              gpio.output(5, 0)
              time.sleep(0.5)
              gpio.output(3, 1)
              gpio.output(5, 1)
              gpio.output(7, 1)
              time.sleep(0.5)
              gpio.output(3, 0)
              gpio.output(5, 0)
              gpio.output(7, 0)
              time.sleep(0.5)
              gpio.output(5, 1)
              time.sleep(0.5)
              gpio.output(5, 0)
              time.sleep(1)
          if i == "g": # ( --. )
              gpio.output(3, 1)
              gpio.output(5, 1)
              gpio.output(7, 1)
              time.sleep(0.5)
              gpio.output(3, 0)
              gpio.output(5, 0)
              gpio.output(7, 0)
              time.sleep(0.5)
              gpio.output(3, 1)
              gpio.output(5, 1)
              gpio.output(7, 1)
              time.sleep(0.5)
              gpio.output(3, 0)
              gpio.output(5, 0)
              gpio.output(7, 0)
              time.sleep(0.5)
              gpio.output(5, 1)
              time.sleep(0.5)
              gpio.output(5, 0)
              time.sleep(1)
          if i == "h": # ( .... )
              gpio.output(5, 1)
              time.sleep(0.5)
              gpio.output(5, 0)
              time.sleep(0.5)
              gpio.output(5, 1)
              time.sleep(0.5)
              gpio.output(5, 0)
              time.sleep(0.5)
              gpio.output(5, 1)
              time.sleep(0.5)
              gpio.output(5, 0)
              time.sleep(0.5)
              gpio.output(5, 1)
              time.sleep(0.5)
              gpio.output(5, 0)
              time.sleep(1)
          if i == "i": # ( .. )
              gpio.output(5, 1)
              time.sleep(0.5)
              gpio.output(5, 0)
              time.sleep(0.5)
              gpio.output(5, 1)
              time.sleep(0.5)
              gpio.output(5, 0)
              time.sleep(1)
          if i == "j": # ( .-- )
              gpio.output(5, 1)
              time.sleep(0.5)
              gpio.output(5, 0)
              time.sleep(0.5)
              gpio.output(3, 1)
              gpio.output(5, 1)
              gpio.output(7, 1)
              time.sleep(0.5)
              gpio.output(3, 0)
              gpio.output(5, 0)
              gpio.output(7, 0)
              time.sleep(0.5)
              gpio.output(3, 1)
              gpio.output(5, 1)
              gpio.output(7, 1)
              time.sleep(0.5)
              gpio.output(3, 0)
              gpio.output(5, 0)
              gpio.output(7, 0)
              time.sleep(1)
          if i == "k": # ( -.- )
              gpio.output(3, 1)
              gpio.output(5, 1)
              gpio.output(7, 1)
              time.sleep(0.5)
              gpio.output(3, 0)
              gpio.output(5, 0)
              gpio.output(7, 0)
              time.sleep(0.5)
              gpio.output(5, 1)
              time.sleep(0.5)
              gpio.output(5, 0)
              time.sleep(0.5)
              gpio.output(3, 1)
              gpio.output(5, 1)
              gpio.output(7, 1)
              time.sleep(0.5)
              gpio.output(3, 0)
              gpio.output(5, 0)
              gpio.output(7, 0)
              time.sleep(1)
          if i == "l": # ( .-.. )
              gpio.output(5, 1)
              time.sleep(0.5)
              gpio.output(5, 0)
              time.sleep(0.5)
              gpio.output(3, 1)
              gpio.output(5, 1)
              gpio.output(7, 1)
              time.sleep(0.5)
              gpio.output(3, 0)
              gpio.output(5, 0)
              gpio.output(7, 0)
              time.sleep(0.5)
              gpio.output(5, 1)
              time.sleep(0.5)
              gpio.output(5, 0)
              time.sleep(0.5)
              gpio.output(5, 1)
              time.sleep(0.5)
              gpio.output(5, 0)
              time.sleep(1)
          if i == "m": # ( -- )
              gpio.output(3, 1)
              gpio.output(5, 1)
              gpio.output(7, 1)
              time.sleep(0.5)
              gpio.output(3, 0)
              gpio.output(5, 0)
              gpio.output(7, 0)
              time.sleep(0.5)
              gpio.output(3, 1)
              gpio.output(5, 1)
              gpio.output(7, 1)
              time.sleep(0.5)
              gpio.output(3, 0)
              gpio.output(5, 0)
              gpio.output(7, 0)
              time.sleep(1)
          if i == "n": # ( -. )
              gpio.output(3, 1)
              gpio.output(5, 1)
              gpio.output(7, 1)
              time.sleep(0.5)
              gpio.output(3, 0)
              gpio.output(5, 0)
              gpio.output(7, 0)
              time.sleep(0.5)
              gpio.output(5, 1)
              time.sleep(0.5)
              gpio.output(5, 0)
              time.sleep(1)
          if i == "o": # ( --- )
              gpio.output(3, 1)
              gpio.output(5, 1)
              gpio.output(7, 1)
              time.sleep(0.5)
              gpio.output(3, 0)
              gpio.output(5, 0)
              gpio.output(7, 0)
              time.sleep(0.5)
              gpio.output(3, 1)
              gpio.output(5, 1)
              gpio.output(7, 1)
              time.sleep(0.5)
              gpio.output(3, 0)
              gpio.output(5, 0)
              gpio.output(7, 0)
              time.sleep(0.5)
              gpio.output(3, 1)
              gpio.output(5, 1)
              gpio.output(7, 1)
              time.sleep(0.5)
              gpio.output(3, 0)
              gpio.output(5, 0)
              gpio.output(7, 0)
              time.sleep(1)
          if i == "p": # ( .--. )
              gpio.output(5, 1)
              time.sleep(0.5)
              gpio.output(5, 0)
              time.sleep(0.5)
              gpio.output(3, 1)
              gpio.output(5, 1)
              gpio.output(7, 1)
              time.sleep(0.5)
              gpio.output(3, 0)
              gpio.output(5, 0)
              gpio.output(7, 0)
              time.sleep(0.5)
              gpio.output(3, 1)
              gpio.output(5, 1)
              gpio.output(7, 1)
              time.sleep(0.5)
              gpio.output(3, 0)
              gpio.output(5, 0)
              gpio.output(7, 0)
              time.sleep(0.5)
              gpio.output(5, 1)
              time.sleep(0.5)
              gpio.output(5, 0)
              time.sleep(1)
          if i == "q": # ( --.- )
              gpio.output(3, 1)
              gpio.output(5, 1)
              gpio.output(7, 1)
              time.sleep(0.5)
              gpio.output(3, 0)
              gpio.output(5, 0)
              gpio.output(7, 0)
              time.sleep(0.5)
              gpio.output(3, 1)
              gpio.output(5, 1)
              gpio.output(7, 1)
              time.sleep(0.5)
              gpio.output(3, 0)
              gpio.output(5, 0)
              gpio.output(7, 0)
              time.sleep(0.5)
              gpio.output(5, 1)
              time.sleep(0.5)
              gpio.output(5, 0)
              time.sleep(0.5)
              gpio.output(3, 1)
              gpio.output(5, 1)
              gpio.output(7, 1)
              time.sleep(0.5)
              gpio.output(3, 0)
              gpio.output(5, 0)
              gpio.output(7, 0)
              time.sleep(1)
          if i == "r": #( .-. )
              gpio.output(5, 1)
              time.sleep(0.5)
              gpio.output(5, 0)
              time.sleep(0.5)
              gpio.output(3, 1)
              gpio.output(5, 1)
              gpio.output(7, 1)
              time.sleep(0.5)
              gpio.output(3, 0)
              gpio.output(5, 0)
              gpio.output(7, 0)
              time.sleep(0.5)
              gpio.output(5, 1)
              time.sleep(0.5)
              gpio.output(5, 0)
              time.sleep(1)
          if i == "s": # ( ... )
              gpio.output(5, 1)
              time.sleep(0.5)
              gpio.output(5, 0)
              time.sleep(0.5)
              gpio.output(5, 1)
              time.sleep(0.5)
              gpio.output(5, 0)
              time.sleep(0.5)
              gpio.output(5, 1)
              time.sleep(0.5)
              gpio.output(5, 0)
              time.sleep(1)
          if i == "t": # ( - )
              gpio.output(3, 1)
              gpio.output(5, 1)
              gpio.output(7, 1)
              time.sleep(0.5)
              gpio.output(3, 0)
              gpio.output(5, 0)
              gpio.output(7, 0)
              time.sleep(1)
          if i == "u": # ( ..- )
              gpio.output(5, 1)
              time.sleep(0.5)
              gpio.output(5, 0)
              time.sleep(0.5)
              gpio.output(5, 1)
              time.sleep(0.5)
              gpio.output(5, 0)
              time.sleep(0.5)
              gpio.output(3, 1)
              gpio.output(5, 1)
              gpio.output(7, 1)
              time.sleep(0.5)
              gpio.output(3, 0)
              gpio.output(5, 0)
              gpio.output(7, 0)
              time.sleep(1)
          if i == "v": # ( ...- )
              gpio.output(5, 1)
              time.sleep(0.5)
              gpio.output(5, 0)
              time.sleep(0.5)
              gpio.output(5, 1)
              time.sleep(0.5)
              gpio.output(5, 0)
              time.sleep(0.5)
              gpio.output(5, 1)
              time.sleep(0.5)
              gpio.output(5, 0)
              time.sleep(0.5)
              gpio.output(3, 1)
              gpio.output(5, 1)
              gpio.output(7, 1)
              time.sleep(0.5)
              gpio.output(3, 0)
              gpio.output(5, 0)
              gpio.output(7, 0)
              time.sleep(1)
          if i == "w": # ( .-- )
              gpio.output(5, 1)
              time.sleep(0.5)
              gpio.output(5, 0)
              time.sleep(0.5)
              gpio.output(3, 1)
              gpio.output(5, 1)
              gpio.output(7, 1)
              time.sleep(0.5)
              gpio.output(3, 0)
              gpio.output(5, 0)
              gpio.output(7, 0)
              time.sleep(0.5)
              gpio.output(3, 1)
              gpio.output(5, 1)
              gpio.output(7, 1)
              time.sleep(0.5)
              gpio.output(3, 0)
              gpio.output(5, 0)
              gpio.output(7, 0)
              time.sleep(1)
          if i == "x": # ( -..- )
              gpio.output(3, 1)
              gpio.output(5, 1)
              gpio.output(7, 1)
              time.sleep(0.5)
              gpio.output(3, 0)
              gpio.output(5, 0)
              gpio.output(7, 0)
              time.sleep(0.5)
              gpio.output(5, 1)
              time.sleep(0.5)
              gpio.output(5, 0)
              time.sleep(0.5)
              gpio.output(5, 1)
              time.sleep(0.5)
              gpio.output(5, 0)
              time.sleep(0.5)
              gpio.output(3, 1)
              gpio.output(5, 1)
              gpio.output(7, 1)
              time.sleep(0.5)
              gpio.output(3, 0)
              gpio.output(5, 0)
              gpio.output(7, 0)
              time.sleep(1)
          if i == "y": # ( -.-- )
              gpio.output(3, 1)
              gpio.output(5, 1)
              gpio.output(7, 1)
              time.sleep(0.5)
              gpio.output(3, 0)
              gpio.output(5, 0)
              gpio.output(7, 0)
              time.sleep(0.5)
              gpio.output(5, 1)
              time.sleep(0.5)
              gpio.output(5, 0)
              time.sleep(0.5)
              gpio.output(3, 1)
              gpio.output(5, 1)
              gpio.output(7, 1)
              time.sleep(0.5)
              gpio.output(3, 0)
              gpio.output(5, 0)
              gpio.output(7, 0)
              time.sleep(0.5)
              gpio.output(3, 1)
              gpio.output(5, 1)
              gpio.output(7, 1)
              time.sleep(0.5)
              gpio.output(3, 0)
              gpio.output(5, 0)
              gpio.output(7, 0)
              time.sleep(1)
          if i == "z": # ( --.. )
              gpio.output(3, 1)
              gpio.output(5, 1)
              gpio.output(7, 1)
              time.sleep(0.5)
              gpio.output(3, 0)
              gpio.output(5, 0)
              gpio.output(7, 0)
              time.sleep(0.5)
              gpio.output(3, 1)
              gpio.output(5, 1)
              gpio.output(7, 1)
              time.sleep(0.5)
              gpio.output(3, 0)
              gpio.output(5, 0)
              gpio.output(7, 0)
              time.sleep(0.5)
              gpio.output(5, 1)
              time.sleep(0.5)
              gpio.output(5, 0)
              time.sleep(0.5)
              gpio.output(5, 1)
              time.sleep(0.5)
              gpio.output(5, 0)
              time.sleep(1)
          if i == " ":
              gpio.output(13, 1)
              time.sleep(2)
              gpio.output(11, 0)

          gpio.output(13, 1)    
          time.sleep(0.4)
          gpio.output(13, 0)          
print(j)
gpio.output(3, 1)
gpio.output(5, 1)
gpio.output(7, 1)
gpio.output(11, 1)
gpio.output(13, 1)
time.sleep(3)
gpio.output(3, 0)
gpio.output(5, 0)
gpio.output(7, 0)
gpio.output(11, 0)
gpio.output(13, 0)
